import {randomBytes} from 'node:crypto';
import {mkdirSync,existsSync,realpathSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve,dirname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const supplied=process.argv[2];
const workspace=resolve(supplied??resolve(app,'../localgpt-workspace'));
mkdirSync(workspace,{recursive:true});
const root=realpathSync(workspace);
if(app===root||app.startsWith(root+sep))throw Error('Choose a separate workspace outside the LocalGPT application folder; it contains browser pairing and MCP credentials.');
const tokenPath=resolve(app,'.localmcp-token');
if(!existsSync(tokenPath))writeFileSync(tokenPath,randomBytes(32).toString('hex')+'\n',{mode:0o600,flag:'wx'});
if(!/^[a-f0-9]{64}$/.test(readFileSync(tokenPath,'utf8').trim()))throw Error('Invalid LocalMCP token file');
const config=resolve(app,'.localmcp.env');
if(!existsSync(config))writeFileSync(config,`LOCALGPT_WORKSPACE=${JSON.stringify(root)}\nLOCALMCP_URL=http://127.0.0.1:8876/local\nLOCALMCP_TOKEN_FILE=${JSON.stringify(tokenPath)}\nLOCALMCP_ALLOW_EXEC=true\nLOCALMCP_PUBLIC_URL=\nLOCALMCP_PUBLIC_HOST=\n`,{mode:0o600,flag:'wx'});
else if(supplied)throw Error('Configuration already exists. Edit LOCALGPT_WORKSPACE in .localmcp.env explicitly instead of overwriting it.');
const bun=process.execPath;
writeFileSync(resolve(app,'dist/mcp-config-fused.json'),JSON.stringify({mcpServers:{localgpt:{command:bun,args:[`--env-file=${config}`,resolve(app,'dist/mcp-stdio.mjs')],env:{LOCALGPT_URL:'http://127.0.0.1:8766'}}}},null,2)+'\n');
console.log(`LocalGPT + LocalMCP Compose configuration prepared. Shared workspace: ${root}\nStart both services: docker compose --env-file .localmcp.env up -d --build\nMCP client config: dist/mcp-config-fused.json\nRegister only http://127.0.0.1:8766/mcp in Codex Desktop. Chrome and the extension run on the host.`);
